### PR TITLE
Continues searching for readline if failed to find version 2.11

### PR DESCRIPTION
**Pull request by LeifAndersen**

### CODE REVIEW

**Comment by mflatt** [comment]
It would be nice if the package could work as long as some libeditline other than 2.11 is installed and selected, as opposed to failing whenever 2.11 is installed.
I don't suppose there's a way to detect the bad version by calling some functions?

**Comment by LeifAndersen** [comment]
I agree this would be ideal. I'm just not sure how to do this without enumerating every other version of libedit.

The problem is that when we load just libedit 2 with ffi-lib, we aren't sure if it was 2.11 (or older), or if it's a newer version of libedit (such as 2.0.57).

I suppose one possibility is to collect some known good versions first, try those, if those don't work, then try version 2.11 (and any other known bad versions) if those work, fail, and finally just try libedit 2 on it's own.

Does that seem better to you?

**Comment by mflatt** [comment]
I'm not sure I understand the overall problem. When version 2.11 is loaded, it goes wrong in some way. Is that way of going wrong safely detectable, or is it unpredictable and/or doom for the process?

**Comment by mflatt** [comment]
I found more details in PR 15054. An off-by-one difference for history indexing sounds like something that could be detected, and it also sounds like a problem that the Racket library could work around instead of rejecting the library – and all of that is typical for an FFI binding.

**Comment by LeifAndersen** [comment]
Yeah, I think that's the right solution. I believe python also does this actually. I'll see if I can get that working.

**Comment by LeifAndersen** [comment]
Okay, it should now work properly with old versions of libedit as well as new versions of libedit.

Tested it on OS X 10 and Debian Weezy.

**Comment by samth** [comment]
Merged.

**Pull request closed without merging**
